version: '3'

services:
    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: root
            POSTGRES_USER: root
            POSTGRES_PASSWORD: prisma
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U root -d root']
            interval: 5s
            timeout: 2s
            retries: 20
        volumes:
            - pgdata:/var/lib/postgresql/data
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        environment:
            DATABASE_URL: 'postgresql://root:prisma@postgres_db:5432/root?schema=public'
        depends_on:
            db:
                condition: service_healthy

volumes:
    pgdata:
